services:
  - type: web
    name: dotahunt
    env: php
    buildCommand: "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm install && npm run production"
    startCommand: "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: dotahunt
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: dotahunt_db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: dotahunt_db
    databaseName: dotahunt
    user: dotahunt
    plan: free
